---
- name: Install howdy
  # Since has still no current package, we don't fail all the time.
  # Howdy needs to use a dedicated venv... https://github.com/boltgolt/howdy/issues

  # attention, ansible_distribution_release will break on linux mint. check the nextcloud-client role for a possible workaround
  when: ansible_distribution_major_version <= "22"
  block:
    - name: Add KeepassXC repo using key from URL
      ansible.builtin.deb822_repository:
        name: howdy-ppa
        types: [deb, deb-src]
        uris: https://ppa.launchpadcontent.net/boltgolt/howdy/ubuntu
        suites: ["{{ ansible_distribution_release | lower }}"]
        components: [main]
        signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2802FD7D4CBF1B050BDE8F3D8CEBC97F3E9E1D58"
        state: present
        enabled: true
      become: true
      become_user: root

    - name: Install howdy
      ansible.builtin.apt:
        name: howdy
        update_cache: true
      environment:
        HOWDY_NO_PROMPT: "true"
      become: true
      become_user: root

  rescue:
    - name: Show rescue debug message
      ansible.builtin.debug:
        msg: "Howdy not yet supported on this OS release..."
