---
- name: Install howdy
  block:
    - name: Add KeepassXC repo using key from URL
      ansible.builtin.deb822_repository:
        name: keepassxc-ppa
        types: [deb, deb-src]
        uris: https://ppa.launchpadcontent.net/boltgolt/howdy/ubuntu
        suites: ["{{ ansible_distribution_release|lower }}"]
        components: [main]
        signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2802FD7D4CBF1B050BDE8F3D8CEBC97F3E9E1D58"
        state: present
        enabled: true

    - name: Install howdy
      ansible.builtin.apt:
        name: howdy
        update_cache: true

  rescue:
    - name: Show rescue debug message
      ansible.builtin.debug:
        msg: "Howdy not yet supported on this OS release..."
